name: Aggiorna trends settimanali

on:
  schedule:
    - cron: '0 8 * * 1'  # Ogni lunedì alle 08:00 UTC
  workflow_dispatch:

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
    - name: Clona il repository
      uses: actions/checkout@v3

    - name: Installa Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installa librerie Python
      run: pip install pytrends pandas

    - name: Esegui lo script Python
      run: python update_trends.py

    - name: Commit e push dei dati aggiornati
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add niches.csv
        git commit -m "Aggiorna trend settimanali da Google Trends" || echo "Nessuna modifica da committare"
        git push origin main
